language: node_js
node_js:
  - "10"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
script:
  - yarn run nyc-cache
  - yarn run test-nyc-strict
  - yarn run test-nyc
  - yarn run test-karma && cat .karma_coverage/lcov/lcov.txt | yarn run coveralls
