language: node_js
node_js:
  - "14"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - script:
        - mkdir dist
        - yarn prettier-check
        - yarn build-icons
        - yarn build-less
        - yarn build-package
    - script:
      - export COVERALLS_FLAG_NAME=karma
      - yarn test-karma
      - cat coverage/chrome/karma.lcov | yarn run coveralls
    - script:
      - export COVERALLS_FLAG_NAME=nyc
      - yarn test-nyc
    - script:
      - export NODE_ENV=TEST
      - export COVERALLS_FLAG_NAME=strict
      - yarn test-nyc
    - script:
      - export COVERALLS_FLAG_NAME=ticlo
      - yarn ticlo-test-nyc

notifications:
  webhooks: https://coveralls.io/webhook
