language: node_js
node_js:
  - "14"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
script:
  - mkdir coverage
  - mkdir dist
  - yarn prettier-check
  - yarn test-nyc-strict
  - yarn test-nyc
  - yarn ticlo-test-nyc
  - yarn build-icons
  - yarn build-less
  - yarn build-package
  - yarn test-karma
  - ls coverage -al
after_success:
  - yarn lcov-result-merger 'coverage/**/*.*' | yarn run coveralls
