language: node_js
node_js:
  - "10"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
script:
  - yarn run nyc-cache
  - yarn run test-nyc-strict
  - yarn run test-nyc
  - yarn run test-karma
  - yarn run lcov-result-merger 'coverage/**/*.txt'
  - cat .karma_coverage/lcov/lcov.txt | yarn run coveralls
