language: node_js
node_js:
  - "10"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
script:
  - yarn run bundle-spec
  - yarn run test-karma && cat .karma_coverage/lcov.txt | yarn run coveralls
  - head -30 ./.karma_coverage/lcov.txt
