language: node_js
node_js:
  - "10"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
script:
  - yarn nyc-cache
  - yarn test-nyc-strict
  - yarn test-nyc
  - yarn build-less
  - yarn build-icons
  - yarn test-karma
  - yarn ts-node tool/unify-lcov.ts
after_success:
  - yarn lcov-result-merger 'coverage/**/*.log' | yarn run coveralls
